version: "3.8"

services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    # env_file:
    #   - ./.env
    # environment:
    #   - POSTGRES_HOST=${POSTGRES_HOST}
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    restart: always
    networks:
      - movemakers-network

  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # env_file:
    #   - ./.env
    # environment:
    #   - POSTGRES_HOST=${POSTGRES_HOST}
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    restart: always
    networks:
      - movemakers-network
