version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: movemakers-postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movemakers

  web:
    build: .
    container_name: movemakers-fastapi
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/movemakers
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
