version: "3.8"

services:
  app:
    build: .
    container_name: movemakers-fastapi
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done;
      uvicorn app.main:app --host 0.0.0.0 --reload'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - TEST_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${TEST_POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - db
      - testdb

  db:
    image: postgres:alpine
    container_name: movemakers-postgres
    ports:
      - 5433:5432 # <host_port>:<container_port>
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  testdb:
    image: postgres:alpine
    container_name: test-movemakers-postgres
    ports:
      - 5434:5432 # <host_port>:<container_port>
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  pgdata:
