name: Docker Compose Actions Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker-compose build --no-cache --force-rm

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the Docker image
        run: docker-compose up -d

      - name: Wait for containers to start (adjust sleep time as needed)
        run: sleep 15

      - name: Run Alembic database migrations
        run: |
          docker-compose run web alembic revision --autogenerate
          docker-compose run web alembic upgrade head
